name: Windows Unit Tests
on: push
jobs:
  run-unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.2.1"
      - name: Install Poetry dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
        